name: CI

on: [push, pull_request]

env:
  # Use a sljit version that is known to compile with bpjit-netbsd.
  # This commit is from: Fri Jan 17 11:39:36 2025 +0100
  USE_SLJIT_COMMIT: 85782cfb77ae4f52e06975655aa4d37b08511ba0

jobs:
  build:
    name: ${{ matrix.cmake-build-type }}-build [${{ matrix.compiler }}, cmake-${{ matrix.cmake-version }}]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc-12, clang-14]
        cmake-version: ['3.27']
        cmake-build-type: [Release, RelWithDebInfo]
        include:
          - compiler: gcc-9
            cmake-version: '3.12'
            cmake-build-type: Release
          - compiler: gcc-11
            cmake-version: '3.18'
            cmake-build-type: Release
          - compiler: clang-12
            cmake-version: '3.15'
            cmake-build-type: Release
          - compiler: clang-13
            cmake-version: '3.20'
            cmake-build-type: Release

    steps:
    - name: Prepare
      run: sudo apt install ${{ matrix.compiler }} libpcap-dev

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: ${{ matrix.cmake-version }}

    - uses: actions/checkout@v4

    - name: Download, build and install dependency sljit
      run: |
        mkdir -p $RUNNER_TEMP/install
        DESTDIR=$RUNNER_TEMP/install \
        USE_SLJIT_COMMIT=${{ env.USE_SLJIT_COMMIT }} \
        make install-sljit

    - name: Generate makefiles
      env:
        CC: ${{ matrix.compiler }}
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.cmake-build-type }} -DCMAKE_PREFIX_PATH=$RUNNER_TEMP/install ..

    - name: Build bpfjit
      working-directory: build
      run: VERBOSE=1 make

    - name: Install bpfjit
      working-directory: build
      run: DESTDIR=$RUNNER_TEMP/install make install

    - name: Build and run tests via CMake
      working-directory: build
      run: |
        make bpfjit-test && ./bpfjit-test
        make bpfjit-test-with-pcap && ./bpfjit-test-with-pcap

    - name: Build and run tests via Makefile
      env:
        CC: ${{ matrix.compiler }}
      run: |
        PREFIX=$RUNNER_TEMP/install/usr/local make test
        PREFIX=$RUNNER_TEMP/install/usr/local make test-with-pcap
