name: CI

on: [push, pull_request]

env:
  # Use a sljit version that is known to compile with bpjit-netbsd.
  # This commit is from: Tue Sep 12 21:29:11 2023 -0700
  USE_SLJIT_COMMIT: 3dcdb25754363db2cd34dbd1cd9a6a6b880cadae

jobs:
  build:
    name: ${{ matrix.cmake-build-type }}-build [${{ matrix.compiler }}, cmake-${{ matrix.cmake-version }}]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc-12, clang-14]
        cmake-version: ['3.27']
        cmake-build-type: [Release, RelWithDebInfo]
        include:
          - compiler: gcc-9
            cmake-version: '3.12'
            cmake-build-type: Release
          - compiler: gcc-11
            cmake-version: '3.18'
            cmake-build-type: Release
          - compiler: clang-12
            cmake-version: '3.15'
            cmake-build-type: Release
          - compiler: clang-13
            cmake-version: '3.20'
            cmake-build-type: Release

    steps:
    - name: Prepare
      run: sudo apt install ${{ matrix.compiler }} libpcap-dev

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: ${{ matrix.cmake-version }}

    - uses: actions/checkout@v3

    - name: Create install folder
      run: cmake -E make_directory $RUNNER_TEMP/install

    - name: Download, build and install dependency sljit
      run: |
        DESTDIR=$RUNNER_TEMP/install \
        USE_SLJIT_COMMIT=${{ env.USE_SLJIT_COMMIT }} \
        make install-sljit

    - name: Create build folder
      run: cmake -E make_directory build

    - name: Generate makefiles
      shell: bash
      env:
        CC: ${{ matrix.compiler }}
      working-directory: build
      run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PREFIX_PATH=$RUNNER_TEMP/install ..

    - name: Build bpfjit
      shell: bash
      working-directory: build
      run: VERBOSE=1 make

    - name: Install bpfjit
      shell: bash
      working-directory: build
      run: DESTDIR=$RUNNER_TEMP/install make install

    - name: Build and run tests via CMake
      shell: bash
      working-directory: build
      run: |
        make bpfjit-test && ./bpfjit-test
        make bpfjit-test-with-pcap && ./bpfjit-test-with-pcap

    - name: Build and run tests via Makefile
      shell: bash
      env:
        CC: ${{ matrix.compiler }}
      run: |
        PREFIX=$RUNNER_TEMP/install/usr/local make test
        PREFIX=$RUNNER_TEMP/install/usr/local make test-with-pcap
